//
//  UpaxWorker.swift
//  testUpax-David-Guillermo-Lopez-Vazquez
//
//  Created by David Lopez on 1/25/22.
//  Copyright (c) 2022 UPAX. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol UpaxWorkerInterface {
    func fetchUpaxData(request: UpaxModels.FetchSalinas.Request, completion: @escaping(Result<SalinasData?, Error>) -> Void)
}

class UpaxWorker: UpaxWorkerInterface {
    
    func fetchUpaxData(request: UpaxModels.FetchSalinas.Request, completion: @escaping (Result<SalinasData?, Error>) -> Void) {
        let request = AF.request("https://us-central1-bibliotecadecontenido.cloudfunctions.net/helloWorld")

        request.responseDecodable(of: SalinasData.self) { response in
            switch response.result {
            case .success(let salinas):
                print(salinas)
                completion(.success(salinas))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}
