//
//  UpaxModels.swift
//  testUpax-David-Guillermo-Lopez-Vazquez
//
//  Created by David Lopez on 1/25/22.
//  Copyright (c) 2022 UPAX. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UpaxModels {
    
    enum FetchSalinas {
        struct Request {

        }

        struct Response {
            var salinas: SalinasData
        }

        struct ViewModel {
            var titles: [String]
            var questions: [[Chart]]
        }
    }
}

struct Chart {
    var color: UIColor
    var text: String
    var percentage: Double
}

enum UpaxEnum: Int {
    case name = 0
    case selfie = 1
}
