//
//  UpaxInteractor.swift
//  testUpax-David-Guillermo-Lopez-Vazquez
//
//  Created by David Lopez on 1/25/22.
//  Copyright (c) 2022 UPAX. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpaxBusinessLogic {
    func fetchSalinas(request: UpaxModels.FetchSalinas.Request)
}

protocol UpaxDataStore {
    //var name: String { get set }
}

class UpaxInteractor: UpaxBusinessLogic, UpaxDataStore {
    var presenter: UpaxPresentationLogic?
    var worker: UpaxWorker?

    // MARK: Do something (and send response to UpaxPresenter)
    func fetchSalinas(request: UpaxModels.FetchSalinas.Request) {
        worker = UpaxWorker()
        let request = UpaxModels.FetchSalinas.Request()
        worker?.fetchUpaxData(request: request, completion: { result in
            switch result {
            case .success(let salinas_):
                guard let salinas = salinas_ else {
                    return
                }
                print(salinas)
                let response = UpaxModels.FetchSalinas.Response(salinas: salinas)
                self.presenter?.presentGraphSalinas(response: response)
            case .failure:
                break
            }
        })
    }
}
